### ISSUE TITLE
Add proper content

### ISSUE THREAD

**Issue by julianpoy** [gogi-git/gogi-on-the-go#11]
Currently we only have some basic content in with "keywords". We need to have actual content from the book in.

**Comment by julianpoy** [comment]
@HRWiegand is assigned due to his association with GOGI. Hugh, you will be in charge of this.

**Comment by julianpoy** [comment]
What's the status on this? Milestone 0.1 Beta is coming up fast.

**Comment by HRWiegand** [comment]
fixes #19 please check out
