### ISSUE TITLE
Build main featured page

### ISSUE THREAD

**Issue by julianpoy** [gogi-git/gogi-on-the-go#2]
Main page needs to include featured tip of the particular week. Date detection for content.

**Comment by torch2424** [comment]
Ill work on date detection, sounds fun to me

**Comment by julianpoy** [comment]
This is the date thing. Ive already started working on this in featured-page branch. You are welcome to help if you would like.

**Comment by torch2424** [comment]
Okay Mr. @julianpoy , Sounds good to me :D

**Comment by torch2424** [comment]
We are probably are going to want to use a get method with moment JS to get the ISO Week, which includes leap  year http://momentjs.com/docs/#/get-set/iso-week/

Iso Week dates: https://en.wikipedia.org/wiki/ISO_week_date

**Comment by julianpoy** [comment]
Looks like @torch2424 is taking this over. Now assigning.
