### ISSUE TITLE
Ensure app works on mobile devices before development

### ISSUE THREAD

**Issue by julianpoy** [gogi-git/gogi-on-the-go#5]
We need to do a check to make sure everything is building correctly for mobile before moving too far forward into the project.

**Comment by julianpoy** [comment]
@torch2424 Would you handle this?

**Comment by torch2424** [comment]
Yeah I can do this, I'll test in android

**Comment by torch2424** [comment]
![media-20150621](https://cloud.githubusercontent.com/assets/1448289/8273121/32fa4c3c-1814-11e5-944b-058c14496fa7.png)

Looking Good, and as a bonus, I can build and test android a lot better from my device!
