### ISSUE TITLE
We need development accounts with Google and Apple

### ISSUE THREAD

**Issue by julianpoy** [gogi-git/gogi-on-the-go#7]
This can be paid for by GOGI, however we need to bring this up and make this clear. To publish the mobile versions of this app officially, we will need development accounts with both companies.

**Comment by torch2424** [comment]
I am familiar with the google play developer console, I can definitely help with that

**Comment by julianpoy** [comment]
This looks like our last issue with this project for 0.1 Beta!

**Comment by julianpoy** [comment]
Solved and purchased.
